name: "Tests"

permissions:
  actions: write

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  workflow_dispatch:

env:
  PULMTLN_TOP_DIR: pulmtln
  MFEM_TOP_DIR: mfem
  HYPRE_TOP_DIR: hypre-2.19.0
  METIS_TOP_DIR: metis-4.0.3
  
  HYPRE_ARCHIVE: v2.19.0.tar.gz
  METIS_ARCHIVE: metis-4.0.3.tar.gz
  
jobs:
  builds-and-tests:
    strategy:
      matrix:
        os: [windows-latest]
        target: [opt]
        
    name: ${{ matrix.os }}-${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - name: checkout PULMTLN
      uses: actions/checkout@v3
      with:
        path: ${{ env.PULMTLN_TOP_DIR }}
        ssh-key: ${{secrets.PULMTLN_SSH_KEY}}

    - name: getcmake
      uses: lukka/get-cmake@latest

    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11

    - name: cache MFEM 
      uses: actions/cache@v3
      id: mfem-cache
      with:
        path: ${{ env.MFEM_TOP_DIR }}
        key: mfem-build-windows-opt 
      
    - name: checkout MFEM
      if: steps.mfem-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: mfem/mfem
        path: ${{ env.MFEM_TOP_DIR }}
    
    - name: build MFEM
      if: steps.mfem-cache.outputs.cache-hit != 'true'
      uses: mfem/github-actions/build-mfem@v2.4
      env:
        VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      with:
        os: windows-latest
        target: opt
        mpi: seq
        build-system: cmake
        hypre-dir: ${{ env.HYPRE_TOP_DIR }}
        metis-dir: ${{ env.METIS_TOP_DIR }}
        mfem-dir: ${{ env.MFEM_TOP_DIR }}
    
    # - name: configure PULMTLN
    #   run: cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-release -DVCPKG_MANIFEST_MODE=OFF -S pulmtln -B pulmtln/build
    
    # - name: build PULMTLN
    #   run: cmake --build pulmtln/build --config Release

    # - name: test PULMTLN
    #   run: cd pulmtln && build/bin/Release/pulmtln_tests.exe
        
    