name: "Tests"

# Github actions can use the default "GITHUB_TOKEN". By default, this token
# is set to have permissive access. However, this is not a good practice
# security-wise. Here we use an external action, so we restrict the
# permission to the minimum required.
# When the 'permissions' is set, all the scopes not mentioned are set to the
# most restrictive setting. So the following is enough.
permissions:
  actions: write

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  workflow_dispatch:

env:
  MFEM_TOP_DIR: mfem
  MFEM_REPOSITORY: mfem/mfem
  PULMTLN_TOP_DIR: pulmtln

jobs:
  builds-and-tests:
    strategy:
      matrix:
        os: [windows-latest]
        target: [opt]
        
    name: ${{ matrix.os }}-${{ matrix.target }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    # Checkout 
    - name: checkout PULMTLN
      uses: actions/checkout@v3
      with:
        path: ${{ env.PULMTLN_TOP_DIR }}
        ssh-key: ${{secrets.PULMTLN_SSH_KEY}}

    # vcpkg
    - name: vcpkg build
      uses: johnwason/vcpkg-action@v5
      id: vcpkg
      with:
        pkgs: nlohmann_json gtest
        triplet: x64-windows-release
        token: ${{ github.token }}

    # MFEM 
    - name: cache MFEM (Windows)
      uses: actions/cache@v3
      with:
        path: mfem_cache
        key: ${{ runner.os }}-opt-mfem
    
    
      
        